def keybindings():
    print(" ------------ Programas ------------")
    print(" Win + T = Cambiador de temas")
    print(" Win + Enter = Terminal")
    print(" Win + B = Navegador Web")
    print(" Win + M = Menú Rofi")
    print(" Win + E = Explorador de archivos")
    print(" Win + N = Nitrogen [Fondos de pantalla]")
    print(" Win + Shift + N = Fondo de pantallla aleatorio")
    print(" Win + R = Activa luz nocturna [Redshift]")
    print(" Win + Shift + R = Desactiva luz nocturna")
    print(" Win + S = Tomar captura de pantalla completa")
    print(" Win + Shift + S = Tomar captura recortada")
    print("")
    print(" ------------ Sistema ------------")
    print(" Win + Control + A = Apagar el equipo")
    print(" Win + Control + Z = Reiniciar el equipo")
    print(" Win + Control + Q = Cerrar sesión")
    print(" Win + Control + W = Suspender")
    print(" Win + Control + R = Recargar Qtile")
    print("")
    print(" ------------ Configuración de ventanas ------------")
    print("")
    print(" --- Cambiar entre ventanas ---")
    print(" Win + H = Ventana de la izquierda")
    print(" Win + L = Ventana de la derecha")
    print(" Win + J = Ventana de abajo")
    print(" Win + K = Ventana de arriba")
    print("")
    print(" --- Mover ventanas ---")
    print(" Win + Shift + H = Hacia la izquierda")
    print(" Win + Shift + L = Hacia la derecha")
    print(" Win + Shift + J = Hacia arriba")
    print(" Win + Shift + K = Hacia abajo")
    print("")
    print(" --- Aumentar tamaño de ventanas ---")
    print(" Win + Control + H = Aumentar hacia la izquierda")
    print(" Win + Control + L = Aumentar hacia la derecha")
    print(" Win + Control + J = Aumentar hacia abajo")
    print(" Win + Control + K = Aumentar hacia arriba")

keybindings()
